version: '2'

networks:
  composer_default:
    external: true

services:
  rest-server:
    container_name: rest-server
    build: ./
    networks:
      - composer_default
    ports:
      - 3000:3000
    environment:
      - COMPOSER_CARD=admin@blockchain-network
      - COMPOSER_NAMESPACES=never
      - COMPOSER_AUTHENTICATION=false
      - COMPOSER_MULTIUSER=fals
    volumes:
        - ~/.composer:/home/composer/.composer
